import { starlightEmRulesScript } from './starlight-em-rules-script';
import {
  absolutePoint,
  anchorPoint,
  createFlipperPair,
  createMirroredRollovers,
  offsetLayoutPoint,
  percentPoint,
} from './layout-primitives';
import type { BoardLayoutDefinition } from './layout-schema';

export const starlightEmLayout: BoardLayoutDefinition = {
  name: 'Starlight EM',
  themeId: 'sunburst',
  template: 'solid-state-two-flipper',
  width: 900,
  height: 1400,
  rulesScript: starlightEmRulesScript,
  drainY: 1425,
  launchPosition: absolutePoint(770, 1180),
  materials: {
    playfield: 'playfieldWood',
    walls: 'metalGuide',
  },
  anchors: [
    { id: 'pop-top', point: absolutePoint(450, 260) },
    { id: 'top-lane-center', point: absolutePoint(450, 170) },
    { id: 'left-bank-center', point: absolutePoint(180, 760) },
    { id: 'right-bank-center', point: absolutePoint(720, 760) },
    { id: 'center-spinner', point: absolutePoint(450, 620) },
    { id: 'saucer-pocket', point: absolutePoint(690, 360) },
  ],
  posts: [
    { position: absolutePoint(450, 1140), radius: 18, material: 'rubberPost' },
    { position: absolutePoint(198, 1020), radius: 18, material: 'rubberPost' },
    { position: absolutePoint(702, 1020), radius: 18, material: 'rubberPost' },
    { position: absolutePoint(156, 908), radius: 16, material: 'metalGuide' },
    { position: absolutePoint(744, 908), radius: 16, material: 'metalGuide' },
  ],
  bumpers: [
    {
      position: anchorPoint('pop-top'),
      radius: 42,
      score: 100,
      material: 'rubberPost',
    },
    {
      position: offsetLayoutPoint(anchorPoint('pop-top'), -110, 150),
      radius: 42,
      score: 100,
      material: 'rubberPost',
    },
    {
      position: offsetLayoutPoint(anchorPoint('pop-top'), 110, 150),
      radius: 42,
      score: 100,
      material: 'rubberPost',
    },
  ],
  standupTargets: [
    {
      position: offsetLayoutPoint(anchorPoint('left-bank-center'), -28, -92),
      width: 60,
      height: 18,
      angle: Math.PI / 2,
      score: 500,
      material: 'rubberPost',
    },
    {
      position: offsetLayoutPoint(anchorPoint('left-bank-center'), -12, 0),
      width: 60,
      height: 18,
      angle: Math.PI / 2,
      score: 500,
      material: 'rubberPost',
    },
    {
      position: offsetLayoutPoint(anchorPoint('left-bank-center'), 4, 92),
      width: 60,
      height: 18,
      angle: Math.PI / 2,
      score: 500,
      material: 'rubberPost',
    },
    {
      position: offsetLayoutPoint(anchorPoint('right-bank-center'), 28, -92),
      width: 60,
      height: 18,
      angle: -Math.PI / 2,
      score: 500,
      material: 'rubberPost',
    },
    {
      position: offsetLayoutPoint(anchorPoint('right-bank-center'), 12, 0),
      width: 60,
      height: 18,
      angle: -Math.PI / 2,
      score: 500,
      material: 'rubberPost',
    },
    {
      position: offsetLayoutPoint(anchorPoint('right-bank-center'), -4, 92),
      width: 60,
      height: 18,
      angle: -Math.PI / 2,
      score: 500,
      material: 'rubberPost',
    },
  ],
  saucers: [
    {
      position: anchorPoint('saucer-pocket'),
      radius: 30,
      score: 3000,
      holdSeconds: 0.55,
      ejectSpeed: 920,
      ejectAngle: Math.PI * 0.82,
      material: 'metalGuide',
    },
  ],
  spinners: [
    {
      position: absolutePoint(194, 540),
      length: 92,
      thickness: 10,
      angle: -0.58,
      score: 100,
      material: 'metalGuide',
    },
    {
      position: anchorPoint('center-spinner'),
      length: 110,
      thickness: 10,
      angle: 0,
      score: 100,
      material: 'metalGuide',
    },
  ],
  rollovers: createMirroredRollovers({
    center: anchorPoint('top-lane-center'),
    offsetsX: [-240, -80, 80, 240],
    radius: 22,
    score: 500,
  }),
  guides: [
    {
      start: absolutePoint(94, 1182),
      end: absolutePoint(150, 898),
      thickness: 14,
      material: 'metalGuide',
    },
    {
      start: absolutePoint(214, 1004),
      end: absolutePoint(186, 1268),
      thickness: 18,
      material: 'metalGuide',
    },
    {
      start: absolutePoint(220, 1088),
      end: absolutePoint(364, 1148),
      thickness: 20,
      material: 'rubberPost',
    },
    {
      start: absolutePoint(806, 1182),
      end: absolutePoint(748, 898),
      thickness: 14,
      material: 'metalGuide',
    },
    {
      start: absolutePoint(686, 1004),
      end: absolutePoint(714, 1268),
      thickness: 18,
      material: 'metalGuide',
    },
    {
      start: absolutePoint(680, 1088),
      end: absolutePoint(536, 1148),
      thickness: 20,
      material: 'rubberPost',
    },
    {
      start: absolutePoint(132, 872),
      end: absolutePoint(116, 644),
      thickness: 14,
      material: 'metalGuide',
    },
    {
      start: absolutePoint(116, 644),
      end: absolutePoint(222, 224),
      thickness: 14,
      material: 'metalGuide',
    },
    {
      start: absolutePoint(222, 224),
      end: absolutePoint(414, 124),
      thickness: 14,
      material: 'metalGuide',
    },
    {
      start: absolutePoint(768, 874),
      end: absolutePoint(784, 600),
      thickness: 14,
      material: 'metalGuide',
    },
    {
      start: absolutePoint(784, 600),
      end: absolutePoint(730, 238),
      thickness: 14,
      material: 'metalGuide',
    },
    {
      start: absolutePoint(730, 238),
      end: absolutePoint(492, 126),
      thickness: 14,
      material: 'metalGuide',
    },
    {
      start: percentPoint(0.35, 0.47),
      end: percentPoint(0.65, 0.47),
      thickness: 12,
      material: 'metalGuide',
    },
  ],
  flippers: createFlipperPair({
    leftX: 270,
    rightX: 630,
    y: 1220,
    length: 150,
    thickness: 20,
    restingAngleOffset: 0.28,
    activeAngleOffset: -0.42,
    material: 'flipperRubber',
  }),
};
